version: '3'
services:

  nlu_server:
    container_name: "nlu_server"
    build:
      context: backend
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
      - ./backend/models:/app/models
    ports:
      - "5005:5005"

  action_server:
    container_name: "action_server"
    build:
      context: actions
    volumes:
      - ./actions:/app
      - ./actions/knowledgebase:/app/knowledgebase
    ports:
      - "5055:5055"
    expose:
      - 5055

  nginx:
    container_name: "web_server"
    build:
      context: nginx
    depends_on:
      - nlu_server
      - action_server
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/cert
      - ./nginx/webchat:/usr/share/nginx/html
    ports:
      - "80:80"
      - "444:443"
